### PR TITLE
fix(selector-strip): styles aligned with design side

### PR DESCRIPTION
**Pull request by cathysiller**
JIRA: surf-1699

### LGTM's
- [x] Dev LGTM
- [x] Design LGTM

### CODE REVIEW

**Comment by HelixUI** [comment]
Deploy preview for *helix-ui* processing.

Building with commit 8d927b170f23ed12423794e873996c269279a4cc

https://app.netlify.com/sites/helix-ui/deploys/5cd9b8c10555f20008aa7993

**Comment by araiford** [comment]
Awesome!  Can you change the font to Roboto Medium at 14px aka 0.875rem?

After that, I think this is good to :shipit:

**Comment by araiford** [comment]
LGTM  :shipit:

**Comment by CITguy** [comment]
Will ship in `v0.16.2` on Wednesday 2019-05-15

**Pull request merged**
