### PR TITLE
docs(*): limit available icons in demos

### PR DESCRIPTION
**Pull request by cathysiller**
JIRA: SURF-1298

### LGTM's
- [x] Dev LGTM
- [x] Design LGTM
- [x] Zoom LGTM

# Before
## File Icon
screen shot 2018-08-07 at 6 07 37 pm

## File Selector
screen shot 2018-08-07 at 6 07 45 pm

## File Tile
screen shot 2018-08-07 at 6 07 53 pm

# After
## File Icon
screen shot 2018-08-07 at 6 04 01 pm

## File Selector
screen shot 2018-08-07 at 6 03 31 pm

## File Tile
screen shot 2018-08-07 at 6 05 02 pm

### CODE REVIEW

**Comment by HelixUI** [comment]
Deploy preview for *helix-ui* processing.

Built with commit d834119e19241b62d992eb49cbba8721807026eb

https://app.netlify.com/sites/helix-ui/deploys/5b6a172ac6aed66443841c2f

**Comment by palindromebart** [comment]
@cathysiller looks great! can we add the empty file to the dropdown list?

**Comment by cathysiller** [comment]
@palindromebart good point! added the empty option in the dropdown (when you click the dropdown it is the first option in file icon and file tile, you can view it here https://deploy-preview-307--helix-ui.netlify.com/

**Comment by palindromebart** [comment]
LGTM!

**Pull request merged**
