### PR TITLE
Refactor things

### PR DESCRIPTION
**Pull request by CITguy**
Preview: https://deploy-preview-295--helix-ui.netlify.com/

* fix File Tile CSS
  * 2px border radius
  * correct name jump on loading/not-loading
* fix mixed content issues with Tabs
* add `HelixUI.ICONS` to simplify consumption of the icons.

### LGTM's
- [x] Dev LGTM
- [x] Design LGTM
- [x] Zoom LGTM

### CODE REVIEW

**Comment by CITguy** [comment]
Bump left/right padding on "X" to 12px/0.75rem

**Comment by CITguy** [comment]
hxContentWrapper: remove right padding

**Comment by HelixUI** [comment]
Deploy preview for *helix-ui* processing.

Built with commit b8b84eab149919728640d1d031ab560988a66da0

https://app.netlify.com/sites/helix-ui/deploys/5b61e9493813f05b61d6ff08

**Comment by palindromebart** [comment]
Design LGTM

**Pull request merged**
