### PR TITLE
docs(polyfills): stop using CDN for polyfills

### PR DESCRIPTION
**Pull request by CITguy**
If this works, I will close #181. From the days of debugging, we can only conclude that there's an issue with running the webcomponent polyfills off a CDN and Travis pulling them correctly.
 
### LGTM's
- [x] Dev LGTM

### CODE REVIEW

**Comment by CITguy** [comment]
Attempt | Build 922 | Build 923
----- | ----- | -----
1 | ✅ 2:44 | ✅ 2:48
2 | n/a | n/a
3 | n/a | n/a
4 | n/a | n/a
5 | n/a | n/a

**Comment by CITguy** [comment]
I just remembered that I need to remove the CDN links from the layouts and the data files, too.

**Comment by CITguy** [comment]
Updated to remove all references to the CDN (in both markup and data files).

**Comment by CITguy** [comment]
Attempt | Build 924 | Build 925
----- | ----- | -----
1 | ✅ 2:39 | ✅ 2:42
2 | n/a | n/a
3 | n/a | n/a
4 | n/a | n/a

**Comment by Droogans** [comment]
It works! Thanks for looking into this for me.

**Pull request merged**
